#!/usr/bin/env python3
"""Regenerate the CLove Sublime package's API lists from the engine sources.

The `love_*` names in CLove.sublime-syntax and CLove.sublime-completions are
generated from the `c_funcs[]` tables in src/fhapi/*.c, so they can never drift
from what the engine actually registers.  Run this after adding, renaming or
removing a binding:

    python3 tools/Sublime/CLove/update_api.py

It rewrites the block between the GENERATED markers in CLove.sublime-syntax and
the whole of CLove.sublime-completions.  Callback signatures below are the one
hand-maintained part: they come from the fh_call_function() call sites in
src/fh_mainactivity.c and src/fhapi/{keyboard,mouse,joystick,config}.c.
"""

import collections
import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
SYNTAX = os.path.join(HERE, 'CLove.sublime-syntax')
COMPLETIONS = os.path.join(HERE, 'CLove.sublime-completions')

BEGIN = '  # >>> GENERATED by update_api.py -- do not edit by hand <<<'
END = '  # >>> END GENERATED <<<'

# Areas in the order they appear in the generated `clove_api` variable.
AREA_ORDER = ['graphics', 'geometry', 'image', 'quad', 'font', 'mesh', 'shader',
              'particleSystem', 'window', 'audio', 'keyboard', 'mouse', 'timer',
              'math', 'filesystem', 'ui', 'event', 'misc']

# Lifecycle callbacks: (name, snippet body, short description).  The input
# callbacks take a *single array*, not one parameter per value -- see
# fh_keyboard_keypressed() and friends, which pack everything into one
# fh_new_array() before calling.
CALLBACKS = [
    ('love_load',
     'fn love_load() {\n\tlet self = {};\n\t$0\n\treturn self;\n}',
     'called once; the value it returns is the game state passed to update/draw'),
    ('love_update',
     'fn love_update(dt, self) {\n\t$0\n}',
     'called every frame; dt is seconds since the last frame'),
    ('love_draw',
     'fn love_draw(self) {\n\t$0\n}',
     'called every frame, after love_update'),
    ('love_config',
     'fn love_config(c) {\n\tc.window_title = "${1:My Game}";\n\tc.window_width = ${2:800};\n\tc.window_height = ${3:600};\n\t$0\n}',
     'in config.fh; called once before the window exists'),
    ('love_focus',
     'fn love_focus(focused) {\n\t$0\n}',
     'focused is a bool'),
    ('love_quit',
     'fn love_quit() {\n\t$0\n}',
     'called as the game shuts down'),
    ('love_keypressed',
     'fn love_keypressed(key) {\n\t# key = [name, keycode, isrepeat]\n\t$0\n}',
     'key is the array [name, keycode, isrepeat]'),
    ('love_keyreleased',
     'fn love_keyreleased(key) {\n\t# key = [name, keycode]\n\t$0\n}',
     'key is the array [name, keycode]'),
    ('love_textinput',
     'fn love_textinput(text) {\n\t$0\n}',
     'text is a string'),
    ('love_mousepressed',
     'fn love_mousepressed(m) {\n\t# m = [x, y, button]\n\t$0\n}',
     'm is the array [x, y, button]'),
    ('love_mousereleased',
     'fn love_mousereleased(m) {\n\t# m = [x, y, button]\n\t$0\n}',
     'm is the array [x, y, button]'),
    ('love_wheelmoved',
     'fn love_wheelmoved(y) {\n\t$0\n}',
     'y is a number'),
    ('love_joystickpressed',
     'fn love_joystickpressed(j) {\n\t# j = [id, button]\n\t$0\n}',
     'j is the array [id, button]'),
    ('love_joystickreleased',
     'fn love_joystickreleased(j) {\n\t# j = [id, button]\n\t$0\n}',
     'j is the array [id, button]'),
]

# config.fh keys read by fh_config_load() in src/fhapi/config.c.
CONFIG_KEYS = [
    ('window_title', '"${1:My Game}"', 'string -- window title'),
    ('window_width', '${1:800}', 'number -- window width'),
    ('window_height', '${1:600}', 'number -- window height'),
    ('window_min_width', '${1:320}', 'number -- minimum window width'),
    ('window_min_height', '${1:240}', 'number -- minimum window height'),
    ('window_max_width', '${1:1920}', 'number -- maximum window width'),
    ('window_max_height', '${1:1080}', 'number -- maximum window height'),
    ('window_x', '${1:0}', 'number -- window position on screen'),
    ('window_y', '${1:0}', 'number -- window position on screen'),
    ('window_bordless', '${1:true}', 'bool -- remove the window border'),
    ('window_resizable', '${1:true}', 'bool -- let the user resize the window'),
    ('window_vsync', '${1:true}', 'bool -- enable vsync'),
    ('window_destroy', '${1:true}', 'bool -- destroy the window at once (headless)'),
    ('window_icon', '"${1:icon.png}"', 'string -- path to the window icon'),
    ('window_fullscreen', '${1:true}', 'bool -- go fullscreen'),
    ('window_fullscreentype', '"${1:desktop}"', 'string -- fullscreen type'),
    ('version', '"${1:0.0.0}"', 'string -- expected CLove version'),
]


def read_api():
    """{basename of src/fhapi/*.c: [registered function names]}"""
    groups = collections.OrderedDict()
    for path in sorted(glob.glob(os.path.join(ROOT, 'src', 'fhapi', '*.c'))):
        src = open(path, encoding='utf-8', errors='replace').read()
        parts = src.split('c_funcs[] = {')
        if len(parts) < 2:
            continue
        names = re.findall(r'DEF_FN\((\w+)\)', parts[1].split('};')[0])
        if names:
            groups[os.path.basename(path)] = sorted(set(names))
    if not groups:
        raise SystemExit(f'no bindings found under {ROOT}/src/fhapi')
    return groups


def area_of(name):
    parts = name.split('_')
    return parts[1] if len(parts) > 2 else 'misc'


def render_variables(names):
    areas = collections.defaultdict(list)
    for n in names:
        areas[area_of(n)].append(n)
    unknown = set(areas) - set(AREA_ORDER)
    if unknown:
        raise SystemExit(f'unknown love_<area>_ prefixes {sorted(unknown)}; '
                         f'add them to AREA_ORDER in {os.path.basename(__file__)}')

    out = [BEGIN]
    for area in AREA_ORDER:
        if not areas[area]:
            continue
        # longest first, so an alternation never has to backtrack past a
        # shorter name that is a prefix of a longer one
        body = '|'.join(sorted(areas[area], key=lambda s: (-len(s), s)))
        var = 'clove_' + area.lower()
        # One line per variable: YAML block scalars fold newlines into spaces,
        # which would silently corrupt the alternation.
        out.append(f"  {var}: '{body}'")
        out.append('')
    out.append("  clove_callback: '%s'"
               % '|'.join(sorted((c[0] for c in CALLBACKS),
                                 key=lambda s: (-len(s), s))))
    out.append('')
    out.append("  clove_api: '%s'"
               % '|'.join('{{clove_%s}}' % a.lower()
                          for a in AREA_ORDER if areas[a]))
    out.append(END)
    return '\n'.join(out)


def write_syntax(names):
    text = open(SYNTAX, encoding='utf-8').read()
    lo, hi = text.index(BEGIN), text.index(END) + len(END)
    open(SYNTAX, 'w', encoding='utf-8').write(
        text[:lo] + render_variables(names) + text[hi:])


def write_completions(groups):
    names = sorted({n for v in groups.values() for n in v})
    source_of = {n: f for f, v in groups.items() for n in v}
    completions = []
    for name, body, doc in CALLBACKS:
        completions.append({
            'trigger': name,
            'contents': body,
            'annotation': 'callback',
            'kind': ['snippet', 'c', 'CLove callback'],
            'details': doc,
        })
    for name in names:
        completions.append({
            'trigger': name,
            'contents': f'{name}($0)',
            'annotation': area_of(name),
            'kind': ['function', 'f', 'CLove API'],
            'details': f'src/fhapi/{source_of[name]}',
        })
    for key, value, doc in CONFIG_KEYS:
        completions.append({
            'trigger': key,
            'contents': f'c.{key} = {value};$0',
            'annotation': 'config.fh',
            'kind': ['variable', 'k', 'CLove config'],
            'details': doc,
        })
    completions.append({
        'trigger': 'clovegame',
        'contents': ('fn love_load() {\n\tlet self = {};\n\t$0\n\treturn self;\n}'
                     '\n\nfn love_update(dt, self) {\n}'
                     '\n\nfn love_draw(self) {\n}'
                     '\n\nfn main() {}\n'),
        'annotation': 'skeleton',
        'kind': ['snippet', 's', 'CLove'],
        'details': 'a complete main.fh skeleton',
    })
    doc = {'scope': 'source.fh', 'completions': completions}
    open(COMPLETIONS, 'w', encoding='utf-8').write(
        json.dumps(doc, indent=2, ensure_ascii=False) + '\n')
    return len(completions), len(names)


def main():
    groups = read_api()
    names = sorted({n for v in groups.values() for n in v})
    write_syntax(names)
    total, api = write_completions(groups)
    print(f'{api} API functions from {len(groups)} modules in src/fhapi/')
    print(f'{total} completions written')


if __name__ == '__main__':
    main()
